# Generated by Django 5.2.1 on 2025-05-24 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда пользователь подписался на курс",
                        verbose_name="Дата подписки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если подписка активна",
                        verbose_name="Активна ли подписка",
                    ),
                ),
                (
                    "notification_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email уведомления"),
                            ("site", "Уведомления на сайте"),
                            ("both", "Email и уведомления на сайте"),
                            ("none", "Не уведомлять"),
                        ],
                        default="email",
                        help_text="Как пользователь хочет получать уведомления",
                        max_length=20,
                        verbose_name="Предпочтения уведомлений",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Курс, на который подписан пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, который подписан на курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "подписка",
                "verbose_name_plural": "подписки",
                "ordering": ["-subscribed_at"],
                "unique_together": {("user", "course")},
            },
        ),
    ]
