# Generated by Django 5.2.1 on 2025-05-24 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscribe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribe",
            options={"verbose_name": "подписка", "verbose_name_plural": "подписки"},
        ),
        migrations.RemoveField(
            model_name="subscribe",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="subscribe",
            name="notification_preference",
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="materials.course",
            ),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="subscribed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
