# Generated by Django 5.2.1 on 2025-05-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_owner"),
    ]

    operations = []
